### ISSUE TITLE
#[br = false] is mentioned in the documentation but doesn't exist in the macro?

### ISSUE THREAD

**Issue by lecanard539** [SeriousBug/rust-embed-for-web#7]
Here it says I can do `#[br = false]` to disable brotli: https://github.com/SeriousBug/rust-embed-for-web/blob/e97f2da4449652f04d7c21e25fa999b2ee994b85/README.md?plain=1#L66

But here this attribute doesn't seem to exist: https://github.com/SeriousBug/rust-embed-for-web/blob/e97f2da4449652f04d7c21e25fa999b2ee994b85/impl/src/lib.rs#L81

Am I stupid or is this a mistake in either the documentation or the implementation?

**Comment by SeriousBug** [comment]
Sorry, that looks like a mistake in the implementation! I'll look into it.

**Comment by SeriousBug** [comment]
@all-contributors please add @peroxid for bug report

**Comment by SeriousBug** [comment]
@peroxid Version 11.1.4 has been released with a fix, let me know if that still doesn't work.
